export function isAutogenerated(str: string): boolean {
  const exclamationIndex = str.indexOf('!');
  if (exclamationIndex === 0) {
    return true;
  }

  if (exclamationIndex === 1) {
    return str.startsWith('#');
  }

  return false;
}

export function isDebatable(str: string): boolean {
  const hashIndex = str.indexOf('#');
  if (hashIndex === 0) {
    return true;
  }

  if (hashIndex === 1) {
    return str.startsWith('!');
  }

  return false;
}

export function stripMetacharacters(str: string): string {
  const hashIndex = str.indexOf('#');
  const exclamationIndex = str.indexOf('!');

  const hasBoth =
    (hashIndex === 0 && exclamationIndex === 1) ||
    (hashIndex === 1 && exclamationIndex === 0);

  if (hasBoth) {
    return str.slice(2);
  }

  if (hashIndex === 0 || exclamationIndex === 0) {
    return str.slice(1);
  }

  return str;
}
