/**
 * Steenbergen format utilities.
 *
 * Utilities for parsing Jan van Steenbergen's Interslavic word list format.
 * This format is specific to how data is structured in the master spreadsheet.
 */

export {
  isAutogenerated,
  stripMetacharacters,
  parseMetacharacters,
} from './metacharacters.ts';

export { parseSteenLemma, type SteenLemma } from './parse-lemma.ts';

export { splitSteenLemmas } from './split-lemmas.ts';

export { parseXPos, type XPosParseResult } from './parse-xpos.ts';
