import { describe, test } from 'node:test';
import assert from 'node:assert';

import {
  isAutogenerated,
  parseMetacharacters,
  stripMetacharacters,
} from './metacharacters.ts';

describe('metacharacters', () => {
  const cases: [string, string | undefined][] = [
    ['!råbota', '!'],
    ['#råbota', '#'],
    ['!#råbota', '!#'],
    ['#!råbota', '#!'],
    ['!!råbota', '!!'],
    ['råbota', undefined],
    ['rå!bota', undefined],
    ['', undefined],
  ];

  for (const [input, expected] of cases) {
    test(`parseMetacharacters(${JSON.stringify(input)})`, () => {
      assert.strictEqual(parseMetacharacters(input), expected);
      assert.strictEqual(
        stripMetacharacters(input),
        input.slice((expected ?? '').length),
      );
    });
  }

  for (const [input, expected] of [
    ['!råbota', true],
    ['!#råbota', true],
    ['#!råbota', true],
    ['#råbota', false],
    ['råbota', false],
    ['rå!bota', false],
  ] as [string, boolean][]) {
    test(`isAutogenerated(${JSON.stringify(input)}) === ${expected}`, () => {
      assert.strictEqual(isAutogenerated(input), expected);
    });
  }
});
