name: Import Changes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  import_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Import changes
        run: npm run import

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: import new_interslavic_words_list'
          title: 'Daily dictionary update'
          body: 'This PR was automatically created to import changes from the external source.'
          base: main
          branch: import-changes
          delete-branch: true
          force: true
